### ISSUE TITLE
How to disable drag event and resize event on annotation

### ISSUE THREAD

**Issue by siddharthray** [Emigre/openseadragon-annotations#27]
Hi,
I am trying to disable drag and resize of the annotation. Can you help to give insight how to disable drag and resize on the annotation.

**Comment by emigre** [comment]
Hey @siddharthray, hi. Sorry, I have forgotten about this plugin for a long time, I'm no longer maintaining it. When I did it it was nothing more than an experiment. Please if you need this plugin make sure to create a fork, because I am going to terminate it. Feel free to continue its development if you want.
