### ISSUE TITLE
Add short info on how to use without npm

### ISSUE THREAD

**Issue by thunfischbrot** [Emigre/openseadragon-annotations#7]
In the README it mentions that one can use a package manager, which implies that it is possible to use it without. I am unable to accomplish just that.

I tried including the main.js and others, failing with 
    `Uncaught SyntaxError: Unexpected token import`
It would be great if there was a demo or one line on how to use it without a package manager.

**Comment by Emigre** [comment]
Hey @thunfischbrot. I have created a [branch in this repo](https://github.com/Emigre/OA-example/tree/without-npm) where you can see a project that does not depend on npm, so you can use it as an example.

You can just open `index.html` and it will work. The images in OpenSeadragon won't show correctly, though. This is because OpenSeadragon searches for the images in the root folder, you will need to start a local server for that to work properly.

You can start a local server in many ways. If you have Node.js installed, [http-server](https://www.npmjs.com/package/http-server) is an easy way, for example. You just have to install it globally with `npm i -g http-server` and then execute it in that example's folder with `http-server .`. If you use Python, you can start a local server like this: `python -m SimpleHTTPServer 8000`.

You are totally correct, the project needs some examples of usage and better docs. I'm going to try to release a new version that will have a number of improvements and I will add docs and examples.

cheers!

**Comment by thunfischbrot** [comment]
Thanks, that's great. I also read up on npm and got it running that way locally.
Great idea about adding some more examples!
